// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyApiPrj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250910113357_InitNewStructure")]
    partial class InitNewStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Manufacture", b =>
                {
                    b.Property<int>("ManufacturerIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManufactureCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufactureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ManufacturerIdentifier");

                    b.ToTable("Manufactures", (string)null);

                    b.HasData(
                        new
                        {
                            ManufacturerIdentifier = 1,
                            ManufactureCountry = "Germany",
                            ManufactureName = "Benz"
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufactureTraceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductQuantityInStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductIdentifier");

                    b.HasIndex("ManufactureTraceId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            ProductIdentifier = 1,
                            ManufactureTraceId = 1,
                            ProductName = "SLS",
                            ProductQuantityInStock = 0
                        });
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Manufacture", "ProductManufacture")
                        .WithMany("ManufactureProducts")
                        .HasForeignKey("ManufactureTraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductManufacture");
                });

            modelBuilder.Entity("Manufacture", b =>
                {
                    b.Navigation("ManufactureProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
